services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estoque
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/src/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      PORT: 3001
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: estoque
      JWT_SECRET: troque_este_segredo_em_producao
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:3001
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data:
